version: "3.8"

services:
  gateway:
    build:
      context: .
      dockerfile: GatewayService/Dockerfile
    ports:
      - "5100:7000"
    depends_on:
      - product
      - inventory
      - ordering
      - payment
      - notification
      - email
      - analytics
      - audit
      - cart
      - identity

  product:
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    ports:
      - "5101:7001"

  inventory:
    build:
      context: .
      dockerfile: InventoryService/Dockerfile
    ports:
      - "5102:7002"

  ordering:
    build:
      context: .
      dockerfile: OrderingService/Dockerfile
    ports:
      - "5103:7003"

  cart:
    build:
      context: .
      dockerfile: CartService/Dockerfile
    ports:
      - "5104:7004"

  identity:
    build:
      context: .
      dockerfile: IdentityService/Dockerfile
    ports:
      - "5105:7005"

  notification:
    build:
      context: .
      dockerfile: NotificationService/Dockerfile
    ports:
      - "5106:7006"

  payment:
    build:
      context: .
      dockerfile: PaymentService/Dockerfile
    ports:
      - "5107:7007"

  email:
    build:
      context: .
      dockerfile: EmailService/Dockerfile
    ports:
      - "5108:8080"

  analytics:
    build:
      context: .
      dockerfile: AnalyticsService/Dockerfile
    ports:
      - "5109:7009"

  audit:
    build:
      context: .
      dockerfile: AuditService/Dockerfile
    ports:
      - "5110:7010"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP (för backend-kommunikation)
      - "15672:15672"   # Web UI (för att se köer etc.)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
